const data = [
  {
    id: 1,
    name: "الفرقة الأولى - الفصل الدراسى الأول ",
    subjects: [
      {
        id: 1,
        name: "قراءات باللغة العربيـــــة في مجال التخصص",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 2,
        name: "المتاحف والمعارض التعليمية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 3,
        name: "الرسومات التعليمية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 4,
        name: "أساسيات الحاسب",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 5,
        name: "مدخــل إلى تكنولوجيا التعليم",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 6,
        name: "مدخل إلي العلوم التربوية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 7,
        name: "مدخل إلي العلوم النفسية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
    ],
  },
  {
    id: 2,
    name: "الفرقة الأولى - الفصل الدراسى الثانى ",
    subjects: [
      {
        id: 1,
        name: "أجهزة العروض التعليمية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 2,
        name: "نظم تشغيل الحاسب الآلى",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 3,
        name: "التسجيلات السمعية التعليمية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 4,
        name: "إنتاج الصور الفوتوغرافية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 5,
        name: "قراءات باللغة الأجنبية فى مجال التخصص",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 6,
        name: "مبادئ وطرق تدريس",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
    ],
  },
  {
    id: 3,
    name: "الفرقة الثانية - الفصل الدراسى الأول ",
    subjects: [
      {
        id: 1,
        name: "مقدمة في الشبكات",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 2,
        name: "التكنولوجيا وتفريد التعليم",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 3,
        name: "التصميم التعليمي",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 4,
        name: "تطبيقات الحاسب المكتبية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 5,
        name: "علم نفس النمو",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
    ],
  },
  {
    id: 4,
    name: "الفرقة الثانية - الفصل الدراسى الثانى ",
    subjects: [
      {
        id: 1,
        name: " الانترنت واستخداماته",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 2,
        name: " معالجة الصور والرسومات الرقمية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 3,
        name: " مقدمة في البرمجة",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 4,
        name: " التعليم الالكتروني",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 5,
        name: " مناهج وطرق تدريس",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
      {
        id: 6,
        name: " تاريخ التربية",
        dataUrl: null,
        examsUrl: null,
        videoUrl: null,
      },
    ],
  },
];
